export { ReactComponent as Headershop } from './svgs/Shop.svg';
export { ReactComponent as Facebook } from './svgs/Facebook.svg';
export { ReactComponent as Instagram } from './svgs/Instagram.svg';
export { ReactComponent as Twitter } from './svgs/Twitter.svg';
export { ReactComponent as Youtube } from './svgs/Youtube.svg';
export { ReactComponent as RightArrow } from './svgs/right-arrow.svg';
export { ReactComponent as User } from './svgs/user.svg';
export { ReactComponent as Lock } from './svgs/Lock.svg';
export { ReactComponent as Shops } from './svgs/Shops.svg';
